    import React from 'react';
    import Header from '../components/Header';

    const Jargon = () => {
        return (
            <div className="bg-black min-h-screen w-full text-white flex flex-col justify-center items-center">
                <Header />
                    <div className="px-4 py-8 max-w-screen-md bg-white text-black">
                        <h1 className="text-2xl font-bold mb-4">MVP (Minimum Viable Product):</h1>
                        <p>The most basic version of a product that allows a startup to collect the maximum amount of validated learning about customers with the least effort.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">TG (Target Group):</h1>
                        <p>The specific demographic or audience segment that a product or service is intended to serve or appeal to.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">TAM (Total Addressable Market):</h1>
                        <p>The total market demand for a product or service, representing the maximum revenue opportunity available to a startup.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">SAM (Serviceable Addressable Market):</h1>
                        <p>The portion of the total addressable market that a startup can realistically target and serve with its resources and capabilities.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">SOM (Serviceable Obtainable Market):</h1>
                        <p>The portion of the serviceable addressable market that a startup can effectively capture and acquire as customers.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">GTM (Go-To Market):</h1>
                        <p>The strategy and process a startup uses to bring its product or service to market and acquire customers.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">PMF (Product Market Fit):</h1>
                        <p>The stage at which a startup has developed a product that meets the needs and demands of its target market, resulting in strong customer satisfaction and demand.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">CAC (Customer Acquisition Cost):</h1>
                        <p>The cost associated with acquiring a new customer, including marketing and sales expenses.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">ROAS (Return On Ad Spend):</h1>
                        <p>A metric used to measure the effectiveness of advertising campaigns by comparing the revenue generated to the cost of the advertising.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">MRR (Monthly Recurring Revenue):</h1>
                        <p>The predictable and repeatable revenue generated by a subscription-based business model on a monthly basis.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">CMGR (Compound Monthly Growth Rate):</h1>
                        <p>The average monthly growth rate of a startup's key metrics, calculated on a compounded basis over a specific period.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">GUC (Gross User Churn):</h1>
                        <p>The rate at which customers or users discontinue their subscription or stop using a product or service, without factoring in new additions or upgrades.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">CCC (Customer Carrying Cost):</h1>
                        <p>The total cost incurred by a startup to acquire, serve, and retain customers over a specific period.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">MIS (Management Information System):</h1>
                        <p>A system used by startups to collect, process, and present data and information to support decision-making and management activities.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">GMV (Gross Merchandise Value):</h1>
                        <p>The total value of merchandise sold through a platform or marketplace, before deducting any discounts, returns, or allowances.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">LTV (Lifetime Value of The Customer):</h1>
                        <p>The predicted net profit attributed to the entire future relationship with a customer, taking into account their purchasing behavior, retention, and potential referrals.</p>
                        <h1 className="text-2xl font-bold mt-8 mb-4">CM (Contribution Margin):</h1>
                        <p>The measure of the profitability of a product or service, calculated as the difference between total revenue and variable costs, expressed as a percentage of revenue.</p>
                </div>
            </div>
        );
    }

    export default Jargon;
